#' @name knmf_colours
#' @aliases knmf_colors
#'
#' @title Basic colours of ggKNMF package
#'
#' An eigth-element named vector with rgb codes of basic palette of this package.
#'
#' First two colours: black and red are colours of KNMF logo. Hues used here have less
#' luminance to avoid tiring eyes. Indygo and green are triadic-complementary to red used here.
#' Yellow, orange, blue and pink were generated by random search for the most distingushible set
#' (with Polychrome package), were search started from colours adjacent with red and indygo.
#'
#' Some modifications were made then to obtain better look for color-blind viewers. First six colours
#' of this palette should be at least moderatly distinguishible for them.
#'
#' This and other palettes can be previewed with \code{\link{colour_preview}} function.
#'
#' @format Named vector with eight elements
#'
#' @source Harmonic colours were obtained with help of \url{http://paletton.com}
#'
#' @seealso \code{\link{colour_preview}}, \code{\link{scale_colour_discrete_knmf}}
"knmf_colours"

#' @rdname knmf_colours
"knmf_colors"
